apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
  namespace: marketplace
spec:
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
        - name: postgis
          image: postgis/postgis:13-3.1
          env:
            - name: POSTGRES_USER
              value: "scorpio"
            - name: POSTGRES_PASSWORD
              value: "scorpio"
            - name: POSTGRES_DB
              value: "scorpio"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgis
  namespace: marketplace
spec:
  ports:
    - port: 5432
  selector:
    app: postgis
