apiVersion: apps/v1
kind: Deployment
metadata:
  name: scorpio-engine
  namespace: marketplace
spec:
  selector:
    matchLabels:
      app: scorpio
  template:
    metadata:
      labels:
        app: scorpio
    spec:
      containers:
        - name: broker
          image: fiware/orion:3.10.1
          command: ["/usr/bin/contextBroker"]
          args: 
            - "-fg" 
            - "-dbhost"
            - "mongodb-bae"
            - "-dbuser"
            - "root"        # Gebruiker uit je mongo config
            - "-dbpwd"
            - "password"    # Wachtwoord uit je mongo config
            - "-db"
            - "orion" 
            - "-multiservice"
          ports:
            - containerPort: 1026
---
apiVersion: v1
kind: Service
metadata:
  name: scorpio
  namespace: marketplace
spec:
  ports:
    - port: 1026
      targetPort: 1026
  selector:
    app: scorpio