# TMForum API Stack voor MarkKlerkx/DOMEMarketplace
# Alle services wijzen naar http://scorpio:1026
---
apiVersion: v1
kind: List
items:
{{- $services := list "party-catalog" "product-catalog" "product-inventory" "product-ordering-management" "customer-management" "account" "usage-management" "usage-consumption" "resource-catalog" "resource-function-activation" "resource-inventory" "service-catalog" "agreement" }}
{{- range $service := $services }}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: tmforum-{{ $service }}
    namespace: marketplace
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: tmforum-{{ $service }}
    template:
      metadata:
        labels:
          app: tmforum-{{ $service }}
      spec:
        containers:
          - name: api
            image: quay.io/fiware/tmforum-{{ $service }}:0.15.0
            env:
              - name: NGSI_LD_URL
                value: "http://scorpio:1026"
            ports:
              - containerPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    name: tmforum-{{ $service }}
    namespace: marketplace
  spec:
    ports:
      - port: 8080
        targetPort: 8080
    selector:
      app: tmforum-{{ $service }}
{{- end }}
