apiVersion: apps/v1
kind: Deployment
metadata:
  name: bae-marketplace
  namespace: marketplace
spec:
  selector:
    matchLabels:
      app: bae-marketplace
  template:
    metadata:
      labels:
        app: bae-marketplace
    spec:
      containers:
        - name: logic-proxy
          # LET OP: dit is de gecorrigeerde naam zonder '-api-'
          image: fiware/biz-ecosystem-logic-proxy:9.1.4-dome
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"
            - name: BAE_LP_PORT
              value: "8004"
            - name: MONGODB_HOST
              value: "mongodb-bae"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USER
              value: "root"
            - name: MONGODB_PASS
              value: "password"
            - name: IDM_URL
              value: "https://login.tunewi.se"
            - name: IDM_REALM
              value: "ascentDataSpaceTrust"
            - name: OIDC_CLIENT_ID
              value: "business-ecosystem"
            - name: OIDC_CLIENT_SECRET
              value: "JxAiyYRXic4S6arkV191kMaPzMUJ5t5S"
            # Hostnames voor de 12 TMForum services
            - name: TMF_PARTY_HOST
              value: "tmforum-party-catalog"
            - name: TMF_CATALOG_HOST
              value: "tmforum-product-catalog"
            - name: TMF_INVENTORY_HOST
              value: "tmforum-product-inventory"
            - name: TMF_ORDERING_HOST
              value: "tmforum-product-ordering-management"
          ports:
            - containerPort: 8004
