# 1. Charging Backend Service
apiVersion: v1
kind: Service
metadata:
  name: bae-charging-backend
  namespace: marketplace
spec:
  ports:
    - port: 8006
      targetPort: 8006
  selector:
    app: bae-charging-backend
---
# 2. BAE Marketplace Service (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: bae-marketplace-test
  namespace: marketplace
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8004
      nodePort: 30080
  selector:
    app: bae-marketplace
---
# 3. Charging Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bae-charging-backend
  namespace: marketplace
spec:
  selector:
    matchLabels:
      app: bae-charging-backend
  template:
    metadata:
      labels:
        app: bae-charging-backend
    spec:
      containers:
        - name: charging-backend
          image: fiware/biz-ecosystem-charging-backend:latest
          env:
            - name: NODE_ENV
              value: "production"
            - name: BAE_CB_MONGO_SERVER
              value: "mongodb-bae"
            - name: BAE_CB_MONGO_PORT
              value: "27017"
            - name: BAE_CB_MONGO_DB
              value: "admin"
            - name: BAE_CB_MONGO_USER
              value: "root"
            - name: BAE_CB_MONGO_PASS
              value: "password"
            - name: BAE_CB_PAYMENT_METHOD
              value: "None"
            - name: BAE_SERVICE_HOST
              value: "https://dome.ascent-it.com"
          ports:
            - containerPort: 8006
---
# 4. Logic Proxy (BAE) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bae-marketplace
  namespace: marketplace
spec:
  selector:
    matchLabels:
      app: bae-marketplace
  template:
    metadata:
      labels:
        app: bae-marketplace
    spec:
      containers:
        - name: logic-proxy
          image: fiware/biz-ecosystem-logic-proxy:latest
          env:
            - name: NODE_ENV
              value: "production"

            # Basis URL van de marketplace zelf
            - name: BAE_SERVICE_HOST
              value: "https://dome.ascent-it.com"

            # OAUTH2 / KEYCLOAK
            - name: BAE_LP_OAUTH2_PROVIDER
              value: "keycloak"

            # Basis-URL van Keycloak (zonder /realms/...)
            - name: BAE_LP_OAUTH2_SERVER
              value: "https://login.tunewi.se"

            # Realm forceren: voorkomt fallback naar 'master'
            - name: BAE_LP_OIDC_REALM
              value: "ascentDataSpaceTrust"

            # Client-config voor de BAE in Keycloak
            - name: BAE_LP_OAUTH2_CLIENT_ID
              value: "business-ecosystem"
              
            - name: BAE_LP_OAUTH2_CLIENT_SECRET
              value: "JxAiyYRXic4S6arkV191kMaPzMUJ5t5S"

            # Callback-URL zoals in de Keycloak-client geregistreerd
            - name: BAE_LP_OAUTH2_CALLBACK
              value: "https://dome.ascent-it.com:30080/auth/keycloak/callback"

            # Roles
            - name: BAE_LP_OAUTH2_ADMIN_ROLE
              value: "admin"
            - name: BAE_LP_OAUTH2_SELLER_ROLE
              value: "seller"
            - name: BAE_LP_OAUTH2_ORG_ADMIN_ROLE
              value: "orgAdmin"

            # Database
            - name: BAE_LP_MONGO_SERVER
              value: "mongodb-bae"
            - name: BAE_LP_MONGO_DB
              value: "admin"
            - name: BAE_LP_MONGO_USER
              value: "root"
            - name: BAE_LP_MONGO_PASS
              value: "password"

            # Link naar Charging Backend
            - name: BAE_CB_LOCAL_SITE
              value: "http://bae-charging-backend:8006/"
          ports:
            - containerPort: 8004
