apiVersion: v1
kind: Service
metadata:
  name: bae-charging-backend
  namespace: marketplace
spec:
  ports:
    - name: standard
      port: 8006
      targetPort: 8006
  selector:
    app: bae-charging-backend
---
apiVersion: v1
kind: Service
metadata:
  name: bae-marketplace-test
  namespace: marketplace
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8004
      nodePort: 30080
  selector:
    app: bae-marketplace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bae-charging-backend
  namespace: marketplace
spec:
  selector:
    matchLabels:
      app: bae-charging-backend
  template:
    metadata:
      labels:
        app: bae-charging-backend
    spec:
      containers:
        - name: charging-backend
          image: fiware/biz-ecosystem-charging-backend:latest
          env:
            - name: NODE_ENV
              value: "production"
            - name: BAE_CB_MONGO_SERVER
              value: "mongodb-bae"
            - name: BAE_CB_MONGO_PORT
              value: "27017"
            - name: BAE_CB_MONGO_DB
              value: "admin"
            - name: BAE_CB_MONGO_USER
              value: "root"
            - name: BAE_CB_MONGO_PASS
              value: "password"
            - name: BAE_SERVICE_HOST
              value: "https://dome.ascent-it.com/"
          ports:
            - containerPort: 8006
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bae-marketplace
  namespace: marketplace
spec:
  selector:
    matchLabels:
      app: bae-marketplace
  template:
    metadata:
      labels:
        app: bae-marketplace
    spec:
      initContainers:
      - name: init-network
        image: busybox:1.28
        command: ['sh', '-c', 'nslookup bae-charging-backend.marketplace.svc.cluster.local | grep "Address" | tail -n1 | awk "{print \$3}" > /etc/network-info/backend-ip']
        volumeMounts:
        - name: network-info
          mountPath: /etc/network-info
      containers:
        - name: logic-proxy
          image: fiware/biz-ecosystem-logic-proxy:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              BACKEND_IP=$(cat /etc/network-info/backend-ip)
              echo "$BACKEND_IP host.docker.internal" >> /etc/hosts
              echo "$BACKEND_IP charging.docker" >> /etc/hosts
              if [ -f /entrypoint.sh ]; then exec /entrypoint.sh; else exec ./entrypoint.sh; fi
          env:
            - name: NODE_ENV
              value: "production"
            - name: BAE_SERVICE_HOST
              value: "https://dome.ascent-it.com/"
            - name: TRUST_PROXY
              value: "true"
            # Backend Koppeling
            - name: BAE_CB_HOST
              value: "bae-charging-backend"
            - name: BAE_CB_PORT
              value: "8006"
            - name: BAE_CB_LOCAL_SITE
              value: "http://bae-charging-backend:8006/"
            # TM Forum API's
            - name: BAE_LP_CATALOG_HOST
              value: "http://bae-charging-backend:8006"
            - name: BAE_LP_INVENTORY_HOST
              value: "http://bae-charging-backend:8006"
            - name: BAE_LP_ORDERING_HOST
              value: "http://bae-charging-backend:8006"
            # OAUTH2 / Keycloak Config
            - name: BAE_LP_OAUTH2_PROVIDER
              value: "keycloak"
            - name: BAE_LP_OAUTH2_SERVER
              value: "https://login.tunewi.se"
            - name: BAE_LP_OIDC_REALM
              value: "ascentDataSpaceTrust"
            - name: BAE_LP_OAUTH2_CLIENT_ID
              value: "business-ecosystem"
            - name: BAE_LP_OAUTH2_CLIENT_SECRET
              value: "JxAiyYRXic4S6arkV191kMaPzMUJ5t5S"
            - name: BAE_LP_OAUTH2_CALLBACK
              value: "https://dome.ascent-it.com/auth/keycloak/callback"
            # Rollen Mapping
            - name: BAE_LP_OAUTH2_ADMIN_ROLE
              value: "admin"
            - name: BAE_LP_OAUTH2_SELLER_ROLE
              value: "seller"
            - name: BAE_LP_OAUTH2_CONSUMER_ROLE
              value: "consumer"
            - name: BAE_LP_OAUTH2_ORG_ADMIN_ROLE
              value: "orgAdmin"
            # Database
            - name: BAE_LP_MONGO_SERVER
              value: "mongodb-bae"
            - name: BAE_LP_MONGO_DB
              value: "admin"
            - name: BAE_LP_MONGO_USER
              value: "root"
            - name: BAE_LP_MONGO_PASS
              value: "password"
          volumeMounts:
          - name: network-info
            mountPath: /etc/network-info
          ports:
            - containerPort: 8004
      volumes:
      - name: network-info
        emptyDir: {}
