apiVersion: apps/v1
kind: Deployment
metadata:
  name: bae-marketplace
  namespace: marketplace
spec:
  selector:
    matchLabels:
      app: bae-marketplace
  template:
    metadata:
      labels:
        app: bae-marketplace
    spec:
      containers:
        - name: logic-proxy
          image: fiware/biz-ecosystem-logic-proxy:9.15.2
          env:
            # Doel 1: VC Login via jouw Keycloak
            - name: IDM_URL
              value: "https://login.tunewi.se"
            - name: IDM_REALM
              value: "ascentDataSpaceTrust"
            - name: OIDC_CLIENT_ID
              value: "business-ecosystem"
            - name: OIDC_CLIENT_SECRET
              value: "JxAiyYRXic4S6arkV191kMaPzMUJ5t5S"
            # Doel 2: Koppeling naar Database
            - name: MONGODB_HOST
              value: "mongodb-bae"
            # Doel 3: Koppeling naar TMForum API's
            - name: TMF_CATALOG_HOST
              value: "tmforum-product-catalog"