apiVersion: apps/v1
kind: Deployment
metadata:
  name: scorpio
  namespace: marketplace
spec:
  selector:
    matchLabels:
      app: scorpio
  template:
    metadata:
      labels:
        app: scorpio
    spec:
      containers:
        - name: scorpio
          image: scorpiobroker/all-in-one-runner:java-kafka-4.1.10
          env:
            - name: DBHOST
              value: postgis # Zorg dat je een simpele postgis pod hebt draaien
            - name: QUARKUS_LOG_LEVEL
              value: INFO
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: scorpio
  namespace: marketplace
spec:
  ports:
    - port: 1026
      targetPort: 9090
  selector:
    app: scorpio