# Voorbeeld voor de Product Catalog (herhaal dit voor Ordering en Party)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmforum-product-catalog
  namespace: marketplace
spec:
  selector:
    matchLabels:
      app: tmforum-product-catalog
  template:
    metadata:
      labels:
        app: tmforum-product-catalog
    spec:
      containers:
        - name: api
          image: quay.io/fiware/tmforum-product-catalog:0.15.0
          env:
            - name: NGSI_LD_URL
              value: "http://scorpio:1026"
---
apiVersion: v1
kind: Service
metadata:
  name: tmforum-product-catalog
  namespace: marketplace
spec:
  ports:
    - port: 8080
  selector:
    app: tmforum-product-catalog